eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 9010
spring:
  application:
    name: service-uc
  zipkin:
      base-url: http://localhost:10000
  sleuth:
    sampler:
      percentage: 1.0
  datasource:
    url: jdbc:mysql://192.168.100.1:3306/test-uc
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

apollo:
  bootstrap:
    enabled: true
    # will inject 'application' and 'TEST1.apollo' namespaces in bootstrap phase
    namespaces: application,TEST3.Pay