eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.100.101:9000/eureka/
server:
  port: 9010
spring:
  application:
    name: service-uc
  datasource:
    url: jdbc:mysql://192.168.100.1:3306/test-uc
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
