server:
  port: 9001


eureka:
  instance:
    hostname: node1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://node2:9002/eureka/

spring:
  application:
    name: node1