eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 9020
spring:
  application:
    name: service-order
  zipkin:
      base-url: http://localhost:10000
  sleuth:
    sampler:
      percentage: 1.0

management:
  security:
    enabled: false



#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 6000 #为了测试Hystrix的fallback效果，此处将超时时间设置成1毫秒